### PR TITLE
Update DynamoDB Data Source example

### PR DESCRIPTION
**Pull request by asuncepeda**

### CODE REVIEW

**Comment by alrocar** [comment]
I'm seeing in [CI](https://github.com/tinybirdco/use-case-examples/actions/runs/10906871176/job/30269150671) that the file is detected as `new file` when it should be a modified one?

```
** Diffs from current commit 'c7eb9938bf5c6b286e08633a337f09858d54e528' and new '450ad3ce779c31d2f1f20035e95128e36c777ba3':
	new file:	iterate_dynamodb/datasources/dynamodb_ci.datasource
```

Maybe it's not being deployed to a workspace where `dynamodb_ci` was already deployed. I'd try to make work the modification otherwise we are not validating the whole thing. Also it's a bit weird that the MR does not add any validation to CI to check that things are working as expected

**Comment by asuncepeda** [comment]
yep, but it's b/c I've created the linked PRs to have them all prepared, but in main the DS isn't created yet (as the previous PR is not merged).
I've tested in other Workspace and it works, when the #364 merges, here we should see the expected workflow

**Comment by alrocar** [comment]
> yep, but it's b/c I've created the linked PRs to have them all prepared, but in main the DS isn't created yet (as the previous PR is not merged). I've tested in other Workspace and it works, when the #364 merges, here we should see the expected workflow

perfect, let's merge the other then and re-run CI 🙏

**Review by alrocar — APPROVED** [review]
Checked in the workspace and works as expected ✨

**Pull request merged**
